server:
  port: 8081

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor
  application:
    name: 'fornecedor'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka  #coloca na loja o end da aplicação eureka